# skip entrypoint for pandoc autostart; needs to be an eisvogel compatible image
image: 
    name: dalibo/pandocker:latest
    entrypoint: [""]

build:
  script:
    - chmod +x ./build.sh
    - ./build.sh
  artifacts:
    paths:
      - ./portfolio.pdf
